#ifndef QTSERIALPORTWIDGETS_GLOBAL_H
#define QTSERIALPORTWIDGETS_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(QTSERIALPORTWIDGETS_LIBRARY)
#  define QTSERIALPORTWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QTSERIALPORTWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSERIALPORTWIDGETS_GLOBAL_H
